/**
 * Deploy script for ROAR Stadium v2 contracts.
 * Target: X Layer Testnet (chainId 195, RPC: https://testrpc.xlayer.tech)
 *
 * Deploy order (dependencies matter):
 *   1. FanPassport
 *   2. WatchLeaderboard
 *   3. FanRewardsPool(usdcAddress, leaderboardAddress)
 *   4. BillingController
 *
 * After deploy, addresses are printed — copy them into .env.local as:
 *   NEXT_PUBLIC_FAN_PASSPORT_ADDRESS=
 *   NEXT_PUBLIC_WATCH_LEADERBOARD_ADDRESS=
 *   NEXT_PUBLIC_FAN_REWARDS_POOL_ADDRESS=
 *   NEXT_PUBLIC_BILLING_CONTROLLER_ADDRESS=
 *
 * Usage:
 *   npx hardhat run contracts/scripts/deploy.ts --network xlayer-testnet --config contracts/hardhat.config.ts
 */

import pkg from "hardhat";
const { ethers } = pkg;
import * as fs from "fs";
import * as path from "path";
import * as dotenv from "dotenv";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

dotenv.config({ path: ".env.local" });

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying contracts with account:", deployer.address);
  console.log("Account balance:", ethers.formatEther(await ethers.provider.getBalance(deployer.address)), "OKB");

  // USDC address — from env (testnet mock or real bridged USDC)
  const usdcAddress =
    process.env.USDC_ADDRESS ??
    process.env.NEXT_PUBLIC_USDC_ADDRESS ??
    "0xd3FFD73C53F139cEBB80b6A524bE280955b3f4db"; // MockUSDC on X Layer Testnet

  console.log("\n📋 Using USDC:", usdcAddress);

  // ── 1. FanPassport ──────────────────────────────────────────────────────────
  console.log("\n🛂 Deploying FanPassport...");
  const FanPassportFactory = await ethers.getContractFactory("FanPassport");
  const fanPassport = await FanPassportFactory.deploy();
  await fanPassport.waitForDeployment();
  const fanPassportAddress = await fanPassport.getAddress();
  console.log("✅ FanPassport deployed to:", fanPassportAddress);

  // ── 2. WatchLeaderboard ─────────────────────────────────────────────────────
  console.log("\n📊 Deploying WatchLeaderboard...");
  const WatchLeaderboardFactory = await ethers.getContractFactory("WatchLeaderboard");
  const watchLeaderboard = await WatchLeaderboardFactory.deploy();
  await watchLeaderboard.waitForDeployment();
  const watchLeaderboardAddress = await watchLeaderboard.getAddress();
  console.log("✅ WatchLeaderboard deployed to:", watchLeaderboardAddress);

  // ── 3. FanRewardsPool ───────────────────────────────────────────────────────
  console.log("\n💰 Deploying FanRewardsPool...");
  const FanRewardsPoolFactory = await ethers.getContractFactory("FanRewardsPool");
  const fanRewardsPool = await FanRewardsPoolFactory.deploy(usdcAddress, watchLeaderboardAddress);
  await fanRewardsPool.waitForDeployment();
  const fanRewardsPoolAddress = await fanRewardsPool.getAddress();
  console.log("✅ FanRewardsPool deployed to:", fanRewardsPoolAddress);

  // ── 4. BillingController ────────────────────────────────────────────────────
  console.log("\n🔒 Deploying BillingController...");
  const BillingControllerFactory = await ethers.getContractFactory("BillingController");
  const billingController = await BillingControllerFactory.deploy();
  await billingController.waitForDeployment();
  const billingControllerAddress = await billingController.getAddress();
  console.log("✅ BillingController deployed to:", billingControllerAddress);

  // ── Summary ─────────────────────────────────────────────────────────────────
  console.log("\n════════════════════════════════════════════════════════");
  console.log("📌 DEPLOYMENT COMPLETE — Copy these to your .env.local:");
  console.log("════════════════════════════════════════════════════════");
  console.log(`NEXT_PUBLIC_FAN_PASSPORT_ADDRESS=${fanPassportAddress}`);
  console.log(`NEXT_PUBLIC_WATCH_LEADERBOARD_ADDRESS=${watchLeaderboardAddress}`);
  console.log(`NEXT_PUBLIC_FAN_REWARDS_POOL_ADDRESS=${fanRewardsPoolAddress}`);
  console.log(`NEXT_PUBLIC_BILLING_CONTROLLER_ADDRESS=${billingControllerAddress}`);
  console.log("════════════════════════════════════════════════════════\n");

  // ── Write addresses.ts ──────────────────────────────────────────────────────
  // Update src/lib/xlayer/addresses.ts with deployed addresses
  const addressesContent = `/**
 * X Layer contract addresses — generated by contracts/scripts/deploy.ts
 * Chain: X Layer Testnet (chainId 1952)
 *
 * DO NOT edit manually. Re-run the deploy script to update.
 */

export const ADDRESSES = {
  FAN_PASSPORT:         (process.env.NEXT_PUBLIC_FAN_PASSPORT_ADDRESS         ?? "${fanPassportAddress}")       as \`0x\${string}\`,
  WATCH_LEADERBOARD:    (process.env.NEXT_PUBLIC_WATCH_LEADERBOARD_ADDRESS     ?? "${watchLeaderboardAddress}")  as \`0x\${string}\`,
  FAN_REWARDS_POOL:     (process.env.NEXT_PUBLIC_FAN_REWARDS_POOL_ADDRESS      ?? "${fanRewardsPoolAddress}")    as \`0x\${string}\`,
  BILLING_CONTROLLER:   (process.env.NEXT_PUBLIC_BILLING_CONTROLLER_ADDRESS    ?? "${billingControllerAddress}") as \`0x\${string}\`,
} as const;

/**
 * Returns true if all contract addresses are configured.
 * Use this guard before any on-chain reads.
 */
export function contractsConfigured(): boolean {
  return (
    !!ADDRESSES.FAN_PASSPORT &&
    !!ADDRESSES.WATCH_LEADERBOARD &&
    !!ADDRESSES.FAN_REWARDS_POOL &&
    !!ADDRESSES.BILLING_CONTROLLER
  );
}
`;

  const addressesPath = path.join(__dirname, "../../src/lib/xlayer/addresses.ts");
  fs.writeFileSync(addressesPath, addressesContent, "utf-8");
  console.log("📄 src/lib/xlayer/addresses.ts updated with deployed addresses.");
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error("❌ Deployment failed:", err);
    process.exit(1);
  });
