/**
 * X Layer contract addresses — generated by contracts/scripts/deploy.ts
 * Chain: X Layer Testnet (chainId 195)
 *
 * DO NOT edit manually. Re-run the deploy script to update.
 */

export const ADDRESSES = {
  FAN_PASSPORT:         (process.env.NEXT_PUBLIC_FAN_PASSPORT_ADDRESS         ?? "0x74Df809b1dfC099E8cdBc98f6a8D1F5c2C3f66f8")       as `0x${string}`,
  WATCH_LEADERBOARD:    (process.env.NEXT_PUBLIC_WATCH_LEADERBOARD_ADDRESS     ?? "0x3f9A1B67F3a3548e0ea5c9eaf43A402d12b6a273")  as `0x${string}`,
  FAN_REWARDS_POOL:     (process.env.NEXT_PUBLIC_FAN_REWARDS_POOL_ADDRESS      ?? "0xFD6D23eE2b6b136E34572fc80cbCd33E9787705e")    as `0x${string}`,
  BILLING_CONTROLLER:   (process.env.NEXT_PUBLIC_BILLING_CONTROLLER_ADDRESS    ?? "0x4DAf17c8142A483B2E2348f56ae0F2cFDAe22ceE") as `0x${string}`,
} as const;

/**
 * Returns true if all contract addresses are configured.
 * Use this guard before any on-chain reads.
 */
export function contractsConfigured(): boolean {
  return (
    !!ADDRESSES.FAN_PASSPORT &&
    !!ADDRESSES.WATCH_LEADERBOARD &&
    !!ADDRESSES.FAN_REWARDS_POOL &&
    !!ADDRESSES.BILLING_CONTROLLER
  );
}

