/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface VARSystemInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CHALLENGE_STAKE"
      | "QUORUM_THRESHOLD"
      | "VOTING_PERIOD"
      | "burnedVideos"
      | "castVote"
      | "challenges"
      | "fanPassport"
      | "hasVoted"
      | "isVideoBurned"
      | "openChallenge"
      | "owner"
      | "renounceOwnership"
      | "settleChallenge"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ChallengeDismissed"
      | "ChallengeOpened"
      | "OwnershipTransferred"
      | "VideoBurned"
      | "VoteCast"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CHALLENGE_STAKE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "QUORUM_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VOTING_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "burnedVideos",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "castVote",
    values: [string, boolean]
  ): string;
  encodeFunctionData(functionFragment: "challenges", values: [string]): string;
  encodeFunctionData(
    functionFragment: "fanPassport",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVideoBurned",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "openChallenge",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "settleChallenge",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "CHALLENGE_STAKE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "QUORUM_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VOTING_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "burnedVideos",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "castVote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "challenges", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fanPassport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isVideoBurned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openChallenge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleChallenge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ChallengeDismissedEvent {
  export type InputTuple = [videoId: string];
  export type OutputTuple = [videoId: string];
  export interface OutputObject {
    videoId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChallengeOpenedEvent {
  export type InputTuple = [videoId: string, challenger: AddressLike];
  export type OutputTuple = [videoId: string, challenger: string];
  export interface OutputObject {
    videoId: string;
    challenger: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VideoBurnedEvent {
  export type InputTuple = [videoId: string];
  export type OutputTuple = [videoId: string];
  export interface OutputObject {
    videoId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    videoId: string,
    voter: AddressLike,
    uphold: boolean
  ];
  export type OutputTuple = [videoId: string, voter: string, uphold: boolean];
  export interface OutputObject {
    videoId: string;
    voter: string;
    uphold: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VARSystem extends BaseContract {
  connect(runner?: ContractRunner | null): VARSystem;
  waitForDeployment(): Promise<this>;

  interface: VARSystemInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CHALLENGE_STAKE: TypedContractMethod<[], [bigint], "view">;

  QUORUM_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  VOTING_PERIOD: TypedContractMethod<[], [bigint], "view">;

  burnedVideos: TypedContractMethod<[arg0: string], [boolean], "view">;

  castVote: TypedContractMethod<
    [videoId: string, uphold: boolean],
    [void],
    "nonpayable"
  >;

  challenges: TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint] & {
        videoId: string;
        challenger: string;
        stakeAmount: bigint;
        votesFor: bigint;
        votesAgainst: bigint;
        openedAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  fanPassport: TypedContractMethod<[], [string], "view">;

  hasVoted: TypedContractMethod<
    [arg0: string, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isVideoBurned: TypedContractMethod<[videoId: string], [boolean], "view">;

  openChallenge: TypedContractMethod<[videoId: string], [void], "payable">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  settleChallenge: TypedContractMethod<[videoId: string], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CHALLENGE_STAKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "QUORUM_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VOTING_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "burnedVideos"
  ): TypedContractMethod<[arg0: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "castVote"
  ): TypedContractMethod<
    [videoId: string, uphold: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "challenges"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint] & {
        videoId: string;
        challenger: string;
        stakeAmount: bigint;
        votesFor: bigint;
        votesAgainst: bigint;
        openedAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "fanPassport"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<[arg0: string, arg1: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isVideoBurned"
  ): TypedContractMethod<[videoId: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "openChallenge"
  ): TypedContractMethod<[videoId: string], [void], "payable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settleChallenge"
  ): TypedContractMethod<[videoId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ChallengeDismissed"
  ): TypedContractEvent<
    ChallengeDismissedEvent.InputTuple,
    ChallengeDismissedEvent.OutputTuple,
    ChallengeDismissedEvent.OutputObject
  >;
  getEvent(
    key: "ChallengeOpened"
  ): TypedContractEvent<
    ChallengeOpenedEvent.InputTuple,
    ChallengeOpenedEvent.OutputTuple,
    ChallengeOpenedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "VideoBurned"
  ): TypedContractEvent<
    VideoBurnedEvent.InputTuple,
    VideoBurnedEvent.OutputTuple,
    VideoBurnedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;

  filters: {
    "ChallengeDismissed(string)": TypedContractEvent<
      ChallengeDismissedEvent.InputTuple,
      ChallengeDismissedEvent.OutputTuple,
      ChallengeDismissedEvent.OutputObject
    >;
    ChallengeDismissed: TypedContractEvent<
      ChallengeDismissedEvent.InputTuple,
      ChallengeDismissedEvent.OutputTuple,
      ChallengeDismissedEvent.OutputObject
    >;

    "ChallengeOpened(string,address)": TypedContractEvent<
      ChallengeOpenedEvent.InputTuple,
      ChallengeOpenedEvent.OutputTuple,
      ChallengeOpenedEvent.OutputObject
    >;
    ChallengeOpened: TypedContractEvent<
      ChallengeOpenedEvent.InputTuple,
      ChallengeOpenedEvent.OutputTuple,
      ChallengeOpenedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "VideoBurned(string)": TypedContractEvent<
      VideoBurnedEvent.InputTuple,
      VideoBurnedEvent.OutputTuple,
      VideoBurnedEvent.OutputObject
    >;
    VideoBurned: TypedContractEvent<
      VideoBurnedEvent.InputTuple,
      VideoBurnedEvent.OutputTuple,
      VideoBurnedEvent.OutputObject
    >;

    "VoteCast(string,address,bool)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
  };
}
