/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BillingControllerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "encodeMatchId"
      | "isLocked"
      | "lockBilling"
      | "matchLocked"
      | "owner"
      | "renounceOwnership"
      | "transferOwnership"
      | "unlockBilling"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BillingLocked"
      | "BillingUnlocked"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "encodeMatchId",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "isLocked", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "lockBilling",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "matchLocked",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockBilling",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "encodeMatchId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isLocked", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lockBilling",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "matchLocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockBilling",
    data: BytesLike
  ): Result;
}

export namespace BillingLockedEvent {
  export type InputTuple = [matchId: BytesLike, reason: string];
  export type OutputTuple = [matchId: string, reason: string];
  export interface OutputObject {
    matchId: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BillingUnlockedEvent {
  export type InputTuple = [matchId: BytesLike];
  export type OutputTuple = [matchId: string];
  export interface OutputObject {
    matchId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BillingController extends BaseContract {
  connect(runner?: ContractRunner | null): BillingController;
  waitForDeployment(): Promise<this>;

  interface: BillingControllerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  encodeMatchId: TypedContractMethod<[matchSlug: string], [string], "view">;

  isLocked: TypedContractMethod<[matchId: BytesLike], [boolean], "view">;

  lockBilling: TypedContractMethod<
    [matchId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  matchLocked: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unlockBilling: TypedContractMethod<
    [matchId: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "encodeMatchId"
  ): TypedContractMethod<[matchSlug: string], [string], "view">;
  getFunction(
    nameOrSignature: "isLocked"
  ): TypedContractMethod<[matchId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lockBilling"
  ): TypedContractMethod<
    [matchId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "matchLocked"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unlockBilling"
  ): TypedContractMethod<[matchId: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "BillingLocked"
  ): TypedContractEvent<
    BillingLockedEvent.InputTuple,
    BillingLockedEvent.OutputTuple,
    BillingLockedEvent.OutputObject
  >;
  getEvent(
    key: "BillingUnlocked"
  ): TypedContractEvent<
    BillingUnlockedEvent.InputTuple,
    BillingUnlockedEvent.OutputTuple,
    BillingUnlockedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "BillingLocked(bytes32,string)": TypedContractEvent<
      BillingLockedEvent.InputTuple,
      BillingLockedEvent.OutputTuple,
      BillingLockedEvent.OutputObject
    >;
    BillingLocked: TypedContractEvent<
      BillingLockedEvent.InputTuple,
      BillingLockedEvent.OutputTuple,
      BillingLockedEvent.OutputObject
    >;

    "BillingUnlocked(bytes32)": TypedContractEvent<
      BillingUnlockedEvent.InputTuple,
      BillingUnlockedEvent.OutputTuple,
      BillingUnlockedEvent.OutputObject
    >;
    BillingUnlocked: TypedContractEvent<
      BillingUnlockedEvent.InputTuple,
      BillingUnlockedEvent.OutputTuple,
      BillingUnlockedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
