/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RoarVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "creatorBps"
      | "creatorEarnings"
      | "deposit"
      | "fanRewardsPool"
      | "owner"
      | "platformBps"
      | "platformRevenue"
      | "platformWallet"
      | "pricePerSecond"
      | "renounceOwnership"
      | "rewardPoolBps"
      | "setPlatformWallet"
      | "setPricePerSecond"
      | "setSettler"
      | "setSplits"
      | "settleSession"
      | "settlers"
      | "transferOwnership"
      | "usdc"
      | "userBalance"
      | "withdrawCreatorEarnings"
      | "withdrawPlatformRevenue"
      | "withdrawUnusedBalance"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CreatorWithdrawal"
      | "Deposited"
      | "FanRewardPoolAccrued"
      | "OwnershipTransferred"
      | "SessionSettled"
      | "SettlerUpdated"
      | "ViewerWithdrawal"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "creatorBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "creatorEarnings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fanRewardsPool",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "platformRevenue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "platformWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pricePerSecond",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardPoolBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPricePerSecond",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSettler",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setSplits",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settleSession",
    values: [AddressLike, AddressLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settlers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawCreatorEarnings",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPlatformRevenue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawUnusedBalance",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "creatorBps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "creatorEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fanRewardsPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pricePerSecond",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardPoolBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPricePerSecond",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setSettler", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setSplits", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "settleSession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "settlers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawCreatorEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPlatformRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawUnusedBalance",
    data: BytesLike
  ): Result;
}

export namespace CreatorWithdrawalEvent {
  export type InputTuple = [creator: AddressLike, amount: BigNumberish];
  export type OutputTuple = [creator: string, amount: bigint];
  export interface OutputObject {
    creator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FanRewardPoolAccruedEvent {
  export type InputTuple = [newTotal: BigNumberish];
  export type OutputTuple = [newTotal: bigint];
  export interface OutputObject {
    newTotal: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SessionSettledEvent {
  export type InputTuple = [
    viewer: AddressLike,
    creator: AddressLike,
    videoHash: BytesLike,
    billableSeconds: BigNumberish,
    totalAmount: BigNumberish,
    creatorShare: BigNumberish,
    platformShare: BigNumberish,
    rewardPoolShare: BigNumberish
  ];
  export type OutputTuple = [
    viewer: string,
    creator: string,
    videoHash: string,
    billableSeconds: bigint,
    totalAmount: bigint,
    creatorShare: bigint,
    platformShare: bigint,
    rewardPoolShare: bigint
  ];
  export interface OutputObject {
    viewer: string;
    creator: string;
    videoHash: string;
    billableSeconds: bigint;
    totalAmount: bigint;
    creatorShare: bigint;
    platformShare: bigint;
    rewardPoolShare: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettlerUpdatedEvent {
  export type InputTuple = [settler: AddressLike, authorized: boolean];
  export type OutputTuple = [settler: string, authorized: boolean];
  export interface OutputObject {
    settler: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ViewerWithdrawalEvent {
  export type InputTuple = [viewer: AddressLike, amount: BigNumberish];
  export type OutputTuple = [viewer: string, amount: bigint];
  export interface OutputObject {
    viewer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RoarVault extends BaseContract {
  connect(runner?: ContractRunner | null): RoarVault;
  waitForDeployment(): Promise<this>;

  interface: RoarVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  creatorBps: TypedContractMethod<[], [bigint], "view">;

  creatorEarnings: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  deposit: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  fanRewardsPool: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  platformBps: TypedContractMethod<[], [bigint], "view">;

  platformRevenue: TypedContractMethod<[], [bigint], "view">;

  platformWallet: TypedContractMethod<[], [string], "view">;

  pricePerSecond: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rewardPoolBps: TypedContractMethod<[], [bigint], "view">;

  setPlatformWallet: TypedContractMethod<
    [_platformWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  setPricePerSecond: TypedContractMethod<
    [_price: BigNumberish],
    [void],
    "nonpayable"
  >;

  setSettler: TypedContractMethod<
    [settler: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  setSplits: TypedContractMethod<
    [
      _creatorBps: BigNumberish,
      _platformBps: BigNumberish,
      _rewardBps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  settleSession: TypedContractMethod<
    [
      viewer: AddressLike,
      creator: AddressLike,
      videoHash: BytesLike,
      billableSeconds: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  settlers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  userBalance: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  withdrawCreatorEarnings: TypedContractMethod<[], [void], "nonpayable">;

  withdrawPlatformRevenue: TypedContractMethod<[], [void], "nonpayable">;

  withdrawUnusedBalance: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "creatorBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "creatorEarnings"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fanRewardsPool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "platformRevenue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "platformWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pricePerSecond"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rewardPoolBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setPlatformWallet"
  ): TypedContractMethod<[_platformWallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPricePerSecond"
  ): TypedContractMethod<[_price: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSettler"
  ): TypedContractMethod<
    [settler: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSplits"
  ): TypedContractMethod<
    [
      _creatorBps: BigNumberish,
      _platformBps: BigNumberish,
      _rewardBps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settleSession"
  ): TypedContractMethod<
    [
      viewer: AddressLike,
      creator: AddressLike,
      videoHash: BytesLike,
      billableSeconds: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settlers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "userBalance"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawCreatorEarnings"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawPlatformRevenue"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawUnusedBalance"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "CreatorWithdrawal"
  ): TypedContractEvent<
    CreatorWithdrawalEvent.InputTuple,
    CreatorWithdrawalEvent.OutputTuple,
    CreatorWithdrawalEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "FanRewardPoolAccrued"
  ): TypedContractEvent<
    FanRewardPoolAccruedEvent.InputTuple,
    FanRewardPoolAccruedEvent.OutputTuple,
    FanRewardPoolAccruedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SessionSettled"
  ): TypedContractEvent<
    SessionSettledEvent.InputTuple,
    SessionSettledEvent.OutputTuple,
    SessionSettledEvent.OutputObject
  >;
  getEvent(
    key: "SettlerUpdated"
  ): TypedContractEvent<
    SettlerUpdatedEvent.InputTuple,
    SettlerUpdatedEvent.OutputTuple,
    SettlerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ViewerWithdrawal"
  ): TypedContractEvent<
    ViewerWithdrawalEvent.InputTuple,
    ViewerWithdrawalEvent.OutputTuple,
    ViewerWithdrawalEvent.OutputObject
  >;

  filters: {
    "CreatorWithdrawal(address,uint256)": TypedContractEvent<
      CreatorWithdrawalEvent.InputTuple,
      CreatorWithdrawalEvent.OutputTuple,
      CreatorWithdrawalEvent.OutputObject
    >;
    CreatorWithdrawal: TypedContractEvent<
      CreatorWithdrawalEvent.InputTuple,
      CreatorWithdrawalEvent.OutputTuple,
      CreatorWithdrawalEvent.OutputObject
    >;

    "Deposited(address,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "FanRewardPoolAccrued(uint256)": TypedContractEvent<
      FanRewardPoolAccruedEvent.InputTuple,
      FanRewardPoolAccruedEvent.OutputTuple,
      FanRewardPoolAccruedEvent.OutputObject
    >;
    FanRewardPoolAccrued: TypedContractEvent<
      FanRewardPoolAccruedEvent.InputTuple,
      FanRewardPoolAccruedEvent.OutputTuple,
      FanRewardPoolAccruedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SessionSettled(address,address,bytes32,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      SessionSettledEvent.InputTuple,
      SessionSettledEvent.OutputTuple,
      SessionSettledEvent.OutputObject
    >;
    SessionSettled: TypedContractEvent<
      SessionSettledEvent.InputTuple,
      SessionSettledEvent.OutputTuple,
      SessionSettledEvent.OutputObject
    >;

    "SettlerUpdated(address,bool)": TypedContractEvent<
      SettlerUpdatedEvent.InputTuple,
      SettlerUpdatedEvent.OutputTuple,
      SettlerUpdatedEvent.OutputObject
    >;
    SettlerUpdated: TypedContractEvent<
      SettlerUpdatedEvent.InputTuple,
      SettlerUpdatedEvent.OutputTuple,
      SettlerUpdatedEvent.OutputObject
    >;

    "ViewerWithdrawal(address,uint256)": TypedContractEvent<
      ViewerWithdrawalEvent.InputTuple,
      ViewerWithdrawalEvent.OutputTuple,
      ViewerWithdrawalEvent.OutputObject
    >;
    ViewerWithdrawal: TypedContractEvent<
      ViewerWithdrawalEvent.InputTuple,
      ViewerWithdrawalEvent.OutputTuple,
      ViewerWithdrawalEvent.OutputObject
    >;
  };
}
