/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RoarballVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CREATOR_BPS"
      | "FAN_BPS"
      | "TREASURY_BPS"
      | "USDC"
      | "VOUCHER_TYPEHASH"
      | "claimCreatorEarnings"
      | "creatorEarnings"
      | "eip712Domain"
      | "fanRewardsPool"
      | "nonces"
      | "owner"
      | "renounceOwnership"
      | "setSettler"
      | "settleVoucher"
      | "settler"
      | "transferOwnership"
      | "treasury"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CreatorClaimed"
      | "EIP712DomainChanged"
      | "OwnershipTransferred"
      | "SettlerUpdated"
      | "VoucherSettled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CREATOR_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "FAN_BPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "TREASURY_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "USDC", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "VOUCHER_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimCreatorEarnings",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "creatorEarnings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fanRewardsPool",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "nonces", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setSettler",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settleVoucher",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "settler", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "CREATOR_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "FAN_BPS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "TREASURY_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "USDC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "VOUCHER_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimCreatorEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creatorEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fanRewardsPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nonces", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setSettler", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "settleVoucher",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "settler", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
}

export namespace CreatorClaimedEvent {
  export type InputTuple = [creator: AddressLike, amount: BigNumberish];
  export type OutputTuple = [creator: string, amount: bigint];
  export interface OutputObject {
    creator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettlerUpdatedEvent {
  export type InputTuple = [previous: AddressLike, next: AddressLike];
  export type OutputTuple = [previous: string, next: string];
  export interface OutputObject {
    previous: string;
    next: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoucherSettledEvent {
  export type InputTuple = [
    user: AddressLike,
    creator: AddressLike,
    totalOwed: BigNumberish,
    creatorCut: BigNumberish,
    fanCut: BigNumberish,
    treasuryCut: BigNumberish,
    nonce: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    creator: string,
    totalOwed: bigint,
    creatorCut: bigint,
    fanCut: bigint,
    treasuryCut: bigint,
    nonce: bigint
  ];
  export interface OutputObject {
    user: string;
    creator: string;
    totalOwed: bigint;
    creatorCut: bigint;
    fanCut: bigint;
    treasuryCut: bigint;
    nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RoarballVault extends BaseContract {
  connect(runner?: ContractRunner | null): RoarballVault;
  waitForDeployment(): Promise<this>;

  interface: RoarballVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CREATOR_BPS: TypedContractMethod<[], [bigint], "view">;

  FAN_BPS: TypedContractMethod<[], [bigint], "view">;

  TREASURY_BPS: TypedContractMethod<[], [bigint], "view">;

  USDC: TypedContractMethod<[], [string], "view">;

  VOUCHER_TYPEHASH: TypedContractMethod<[], [string], "view">;

  claimCreatorEarnings: TypedContractMethod<[], [void], "nonpayable">;

  creatorEarnings: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  fanRewardsPool: TypedContractMethod<[], [string], "view">;

  nonces: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setSettler: TypedContractMethod<
    [_settler: AddressLike],
    [void],
    "nonpayable"
  >;

  settleVoucher: TypedContractMethod<
    [
      user: AddressLike,
      creator: AddressLike,
      totalOwed: BigNumberish,
      nonce: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  settler: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CREATOR_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FAN_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TREASURY_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "USDC"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "VOUCHER_TYPEHASH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claimCreatorEarnings"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "creatorEarnings"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "fanRewardsPool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "nonces"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSettler"
  ): TypedContractMethod<[_settler: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settleVoucher"
  ): TypedContractMethod<
    [
      user: AddressLike,
      creator: AddressLike,
      totalOwed: BigNumberish,
      nonce: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settler"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "CreatorClaimed"
  ): TypedContractEvent<
    CreatorClaimedEvent.InputTuple,
    CreatorClaimedEvent.OutputTuple,
    CreatorClaimedEvent.OutputObject
  >;
  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SettlerUpdated"
  ): TypedContractEvent<
    SettlerUpdatedEvent.InputTuple,
    SettlerUpdatedEvent.OutputTuple,
    SettlerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "VoucherSettled"
  ): TypedContractEvent<
    VoucherSettledEvent.InputTuple,
    VoucherSettledEvent.OutputTuple,
    VoucherSettledEvent.OutputObject
  >;

  filters: {
    "CreatorClaimed(address,uint256)": TypedContractEvent<
      CreatorClaimedEvent.InputTuple,
      CreatorClaimedEvent.OutputTuple,
      CreatorClaimedEvent.OutputObject
    >;
    CreatorClaimed: TypedContractEvent<
      CreatorClaimedEvent.InputTuple,
      CreatorClaimedEvent.OutputTuple,
      CreatorClaimedEvent.OutputObject
    >;

    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SettlerUpdated(address,address)": TypedContractEvent<
      SettlerUpdatedEvent.InputTuple,
      SettlerUpdatedEvent.OutputTuple,
      SettlerUpdatedEvent.OutputObject
    >;
    SettlerUpdated: TypedContractEvent<
      SettlerUpdatedEvent.InputTuple,
      SettlerUpdatedEvent.OutputTuple,
      SettlerUpdatedEvent.OutputObject
    >;

    "VoucherSettled(address,address,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      VoucherSettledEvent.InputTuple,
      VoucherSettledEvent.OutputTuple,
      VoucherSettledEvent.OutputObject
    >;
    VoucherSettled: TypedContractEvent<
      VoucherSettledEvent.InputTuple,
      VoucherSettledEvent.OutputTuple,
      VoucherSettledEvent.OutputObject
    >;
  };
}
