/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace StadiumAdBoard {
  export type AdSlotStruct = {
    category: string;
    advertiser: AddressLike;
    bidAmount: BigNumberish;
    adContentURI: string;
    expiresAt: BigNumberish;
    active: boolean;
  };

  export type AdSlotStructOutput = [
    category: string,
    advertiser: string,
    bidAmount: bigint,
    adContentURI: string,
    expiresAt: bigint,
    active: boolean
  ] & {
    category: string;
    advertiser: string;
    bidAmount: bigint;
    adContentURI: string;
    expiresAt: bigint;
    active: boolean;
  };
}

export interface StadiumAdBoardInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "USDC"
      | "activeSlots"
      | "fanRewardsPool"
      | "gasTreasury"
      | "getActiveSlot"
      | "owner"
      | "pendingBids"
      | "placeBid"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "RevenueDistributed"
      | "SlotWon"
  ): EventFragment;

  encodeFunctionData(functionFragment: "USDC", values?: undefined): string;
  encodeFunctionData(functionFragment: "activeSlots", values: [string]): string;
  encodeFunctionData(
    functionFragment: "fanRewardsPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "gasTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveSlot",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pendingBids", values: [string]): string;
  encodeFunctionData(
    functionFragment: "placeBid",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "USDC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "activeSlots",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fanRewardsPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gasTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveSlot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingBids",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "placeBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RevenueDistributedEvent {
  export type InputTuple = [fanPoolCut: BigNumberish, gasCut: BigNumberish];
  export type OutputTuple = [fanPoolCut: bigint, gasCut: bigint];
  export interface OutputObject {
    fanPoolCut: bigint;
    gasCut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SlotWonEvent {
  export type InputTuple = [
    category: string,
    advertiser: AddressLike,
    bid: BigNumberish
  ];
  export type OutputTuple = [category: string, advertiser: string, bid: bigint];
  export interface OutputObject {
    category: string;
    advertiser: string;
    bid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StadiumAdBoard extends BaseContract {
  connect(runner?: ContractRunner | null): StadiumAdBoard;
  waitForDeployment(): Promise<this>;

  interface: StadiumAdBoardInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  USDC: TypedContractMethod<[], [string], "view">;

  activeSlots: TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, string, bigint, boolean] & {
        category: string;
        advertiser: string;
        bidAmount: bigint;
        adContentURI: string;
        expiresAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  fanRewardsPool: TypedContractMethod<[], [string], "view">;

  gasTreasury: TypedContractMethod<[], [string], "view">;

  getActiveSlot: TypedContractMethod<
    [category: string],
    [StadiumAdBoard.AdSlotStructOutput],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pendingBids: TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, string, bigint, boolean] & {
        category: string;
        advertiser: string;
        bidAmount: bigint;
        adContentURI: string;
        expiresAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  placeBid: TypedContractMethod<
    [
      category: string,
      adContentURI: string,
      bidAmount: BigNumberish,
      durationSeconds: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "USDC"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "activeSlots"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, string, bigint, boolean] & {
        category: string;
        advertiser: string;
        bidAmount: bigint;
        adContentURI: string;
        expiresAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "fanRewardsPool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "gasTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getActiveSlot"
  ): TypedContractMethod<
    [category: string],
    [StadiumAdBoard.AdSlotStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingBids"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, string, bigint, boolean] & {
        category: string;
        advertiser: string;
        bidAmount: bigint;
        adContentURI: string;
        expiresAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "placeBid"
  ): TypedContractMethod<
    [
      category: string,
      adContentURI: string,
      bidAmount: BigNumberish,
      durationSeconds: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RevenueDistributed"
  ): TypedContractEvent<
    RevenueDistributedEvent.InputTuple,
    RevenueDistributedEvent.OutputTuple,
    RevenueDistributedEvent.OutputObject
  >;
  getEvent(
    key: "SlotWon"
  ): TypedContractEvent<
    SlotWonEvent.InputTuple,
    SlotWonEvent.OutputTuple,
    SlotWonEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RevenueDistributed(uint256,uint256)": TypedContractEvent<
      RevenueDistributedEvent.InputTuple,
      RevenueDistributedEvent.OutputTuple,
      RevenueDistributedEvent.OutputObject
    >;
    RevenueDistributed: TypedContractEvent<
      RevenueDistributedEvent.InputTuple,
      RevenueDistributedEvent.OutputTuple,
      RevenueDistributedEvent.OutputObject
    >;

    "SlotWon(string,address,uint256)": TypedContractEvent<
      SlotWonEvent.InputTuple,
      SlotWonEvent.OutputTuple,
      SlotWonEvent.OutputObject
    >;
    SlotWon: TypedContractEvent<
      SlotWonEvent.InputTuple,
      SlotWonEvent.OutputTuple,
      SlotWonEvent.OutputObject
    >;
  };
}
