/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace WatchLeaderboard {
  export type FanEntryStruct = {
    wallet: AddressLike;
    watchSeconds: BigNumberish;
    countryCode: string;
  };

  export type FanEntryStructOutput = [
    wallet: string,
    watchSeconds: bigint,
    countryCode: string
  ] & { wallet: string; watchSeconds: bigint; countryCode: string };
}

export interface WatchLeaderboardInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "advanceWeek"
      | "currentWeekId"
      | "getBoard"
      | "getCurrentBoard"
      | "owner"
      | "renounceOwnership"
      | "settled"
      | "submitWeeklyBoard"
      | "transferOwnership"
      | "weeklyBoard"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LeaderboardSubmitted"
      | "OwnershipTransferred"
      | "WeekAdvanced"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "advanceWeek",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentWeekId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBoard",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentBoard",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "settled",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "submitWeeklyBoard",
    values: [BigNumberish, string, AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "weeklyBoard",
    values: [BigNumberish, string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "advanceWeek",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentWeekId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBoard", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentBoard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "settled", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitWeeklyBoard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "weeklyBoard",
    data: BytesLike
  ): Result;
}

export namespace LeaderboardSubmittedEvent {
  export type InputTuple = [
    weekId: BigNumberish,
    countryCode: string,
    fanCount: BigNumberish
  ];
  export type OutputTuple = [
    weekId: bigint,
    countryCode: string,
    fanCount: bigint
  ];
  export interface OutputObject {
    weekId: bigint;
    countryCode: string;
    fanCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WeekAdvancedEvent {
  export type InputTuple = [newWeekId: BigNumberish];
  export type OutputTuple = [newWeekId: bigint];
  export interface OutputObject {
    newWeekId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WatchLeaderboard extends BaseContract {
  connect(runner?: ContractRunner | null): WatchLeaderboard;
  waitForDeployment(): Promise<this>;

  interface: WatchLeaderboardInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  advanceWeek: TypedContractMethod<[], [void], "nonpayable">;

  currentWeekId: TypedContractMethod<[], [bigint], "view">;

  getBoard: TypedContractMethod<
    [weekId: BigNumberish, countryCode: string],
    [WatchLeaderboard.FanEntryStructOutput[]],
    "view"
  >;

  getCurrentBoard: TypedContractMethod<
    [countryCode: string],
    [WatchLeaderboard.FanEntryStructOutput[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  settled: TypedContractMethod<
    [arg0: BigNumberish, arg1: string],
    [boolean],
    "view"
  >;

  submitWeeklyBoard: TypedContractMethod<
    [
      weekId: BigNumberish,
      countryCode: string,
      wallets: AddressLike[],
      watchSeconds: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  weeklyBoard: TypedContractMethod<
    [arg0: BigNumberish, arg1: string, arg2: BigNumberish],
    [
      [string, bigint, string] & {
        wallet: string;
        watchSeconds: bigint;
        countryCode: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "advanceWeek"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "currentWeekId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBoard"
  ): TypedContractMethod<
    [weekId: BigNumberish, countryCode: string],
    [WatchLeaderboard.FanEntryStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentBoard"
  ): TypedContractMethod<
    [countryCode: string],
    [WatchLeaderboard.FanEntryStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settled"
  ): TypedContractMethod<[arg0: BigNumberish, arg1: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "submitWeeklyBoard"
  ): TypedContractMethod<
    [
      weekId: BigNumberish,
      countryCode: string,
      wallets: AddressLike[],
      watchSeconds: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "weeklyBoard"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: string, arg2: BigNumberish],
    [
      [string, bigint, string] & {
        wallet: string;
        watchSeconds: bigint;
        countryCode: string;
      }
    ],
    "view"
  >;

  getEvent(
    key: "LeaderboardSubmitted"
  ): TypedContractEvent<
    LeaderboardSubmittedEvent.InputTuple,
    LeaderboardSubmittedEvent.OutputTuple,
    LeaderboardSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "WeekAdvanced"
  ): TypedContractEvent<
    WeekAdvancedEvent.InputTuple,
    WeekAdvancedEvent.OutputTuple,
    WeekAdvancedEvent.OutputObject
  >;

  filters: {
    "LeaderboardSubmitted(uint256,string,uint256)": TypedContractEvent<
      LeaderboardSubmittedEvent.InputTuple,
      LeaderboardSubmittedEvent.OutputTuple,
      LeaderboardSubmittedEvent.OutputObject
    >;
    LeaderboardSubmitted: TypedContractEvent<
      LeaderboardSubmittedEvent.InputTuple,
      LeaderboardSubmittedEvent.OutputTuple,
      LeaderboardSubmittedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "WeekAdvanced(uint256)": TypedContractEvent<
      WeekAdvancedEvent.InputTuple,
      WeekAdvancedEvent.OutputTuple,
      WeekAdvancedEvent.OutputObject
    >;
    WeekAdvanced: TypedContractEvent<
      WeekAdvancedEvent.InputTuple,
      WeekAdvancedEvent.OutputTuple,
      WeekAdvancedEvent.OutputObject
    >;
  };
}
