/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFanPassport,
  IFanPassportInterface,
} from "../../../src/VARSystem.sol/IFanPassport";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "holder",
        type: "address",
      },
    ],
    name: "holderToTokenId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IFanPassport__factory {
  static readonly abi = _abi;
  static createInterface(): IFanPassportInterface {
    return new Interface(_abi) as IFanPassportInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFanPassport {
    return new Contract(address, _abi, runner) as unknown as IFanPassport;
  }
}
