/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IFanPassport__factory } from "./IFanPassport__factory";
export { VARSystem__factory } from "./VARSystem__factory";
